medical_warehouse:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('DB_HOST') }}"
      port: 5433
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: raw
  target: dev
